# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29f4d2c252fefee4855f3343b152c0b8a2ee10d75b2dc8a8e47f2133cc941d1448a72c0b334e1cd57bff0daa5bb4ab9fa079d965cdf7db0e740f6293bad8ecc8

test:
  secret_key_base: c4d429361403b2d706419f40961e9bd2858d1290019b1a9ebd1f339521de0af2dc7ef660e8e1b39f8c54724757c7314edd9659d92193e117ba17e7bae7e0343a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
